Feature/24 09 2022/init files table
Just-Programing/forum-api pull request #3
Opened 2022-09-24 21:09 UTC by tungjj

2022-09-26 07:09 UTC, ericchentch requested changes
check review comments, rebase to get new update in abstract mongo repo

2022-09-26 07:09 UTC, ericchentch commented on src/main/java/edunhnil/project/forum/api/controller/FileController.java
> +    @GetMapping(value = "get-files-by-user-id")
change to /get-file for single file, get files for multiple and add prefix such as /user, /public, /admin

2022-09-29 08:40 UTC, ericchentch commented on src/main/java/edunhnil/project/forum/api/config/SecurityConfig.java
> +                                                "/files-controller/user/**")
change to /files not files-controller

2022-09-29 08:41 UTC, ericchentch commented on src/main/java/edunhnil/project/forum/api/controller/FileController.java
> +@RequestMapping(value = "files-controller")
change to /files

2022-09-29 08:41 UTC, ericchentch commented on src/main/java/edunhnil/project/forum/api/controller/FileController.java
> +    @PostMapping(value = "user/create-file")
user/create

2022-09-29 08:41 UTC, ericchentch commented on src/main/java/edunhnil/project/forum/api/controller/FileController.java
> +    @GetMapping(value = "user/get-files-by-user-id")
user/get-files

2022-09-29 08:42 UTC, ericchentch commented on src/main/java/edunhnil/project/forum/api/controller/FileController.java
> +    @GetMapping(value = "user/get-file-by-id")
user/get-file

2022-09-29 08:42 UTC, ericchentch commented on src/main/java/edunhnil/project/forum/api/dto/fileDTO/FileEnum.java
> +public enum FileEnum {
discard this file

2022-10-03 06:43 UTC, tungjj commented on src/main/java/edunhnil/project/forum/api/controller/FileController.java
> +    @GetMapping(value = "get-files-by-user-id")
done

2022-10-03 06:43 UTC, tungjj commented on src/main/java/edunhnil/project/forum/api/config/SecurityConfig.java
> +                                                "/files-controller/user/**")
done

2022-10-03 06:43 UTC, tungjj commented on src/main/java/edunhnil/project/forum/api/controller/FileController.java
> +@RequestMapping(value = "files-controller")
done

2022-10-03 06:44 UTC, tungjj commented
Need to review

2022-10-07 11:31 UTC, ericchentch approved these changes
LG

2022-10-07 11:33 UTC, merged